#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# 这个地方, windows 会有所不同
export GOPATH="${HOME}/go"
export GOROOT="/usr/local/go"

if [[ $PATH != *$GOPATH* ]]; then
    export PATH="${GOPATH}/bin:${PATH}"
fi

if [[ $PATH != *$GOROOT* ]]; then
    export PATH="${GOROOT}/bin:${PATH}"
fi

# staticcheck 静态代码检查
# 官网: https://staticcheck.io/docs/getting-started/
# 请先安装: go install honnef.co/go/tools/cmd/staticcheck@latest
staticcheck ./...